apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  annotations:
    open-cluster-management/created-via: other
  labels:
    cloud: Other
    cluster.open-cluster-management.io/clusterset: default
    clusterID: e103b035-14a4-4bb7-93aa-fecbf077b960
    gitops: local.hub
    local-cluster: "true"
    name: local-cluster
    velero.io/exclude-from-backup: "true"
    vendor: OpenShift
  name: local-cluster
spec:
  hubAcceptsClient: true
  leaseDurationSeconds: 60
  managedClusterClientConfigs:
  - url: https://api.hub.ocplab.com:6443
