apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: argocd-manage-policies
placementRef:
  name: argocd-manage-policies
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: argocd-manage-policies
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: argocd-manage-policies
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - { key: name, operator: In, values: ["local-cluster"] }